#Tomcat
server:
  port: 8080
  context-path: /SEIN

#mysql
spring:
  #环境:pro/dev
  profiles:
    active: pro
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
  #jackson时间格式化
  jackson:
    time-zone: GMT-8
    date-format: yyyy-MM-dd HH:mm:ss
  #thymeleaf配置
  thymeleaf:
      cache: false

#mybatis
mybatis:
  type-aliases-package: com.sein.pojo.po

#通用Mapper
mapper:
  mappers: com.sein.utils.MyMapper
  not-empty: false
  identity: MYSQL

#pageHelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
#lockback配置
logging:
  file: D://sein/sein.log

